import { useEffect, useState, type FormEvent } from "react";
import { Check, Plus, Trash2 } from "lucide-react";
import { goalsApi } from "../api/productivityApi";
import { extractErrorMessage } from "../api/client";
import type { Goal } from "../types/academic";

export default function GoalsPage() {
  const [goals, setGoals] = useState<Goal[]>([]); const [title, setTitle] = useState(""); const [targetDate, setTargetDate] = useState(""); const [error, setError] = useState<string | null>(null);
  useEffect(() => { goalsApi.list().then(setGoals).catch((e) => setError(extractErrorMessage(e, "Unable to load goals"))); }, []);
  async function add(e: FormEvent) { e.preventDefault(); try { const goal = await goalsApi.create({ title, targetDate: targetDate || null, progressPercent: 0, status: "ACTIVE" }); setGoals((v) => [...v, goal]); setTitle(""); setTargetDate(""); } catch (err) { setError(extractErrorMessage(err, "Unable to create goal")); } }
  async function complete(goal: Goal) { try { const saved = await goalsApi.complete(goal.id); setGoals((v) => v.map((x) => x.id === saved.id ? saved : x)); } catch (err) { setError(extractErrorMessage(err, "Unable to complete goal")); } }
  async function remove(id: number) { try { await goalsApi.delete(id); setGoals((v) => v.filter((x) => x.id !== id)); } catch (err) { setError(extractErrorMessage(err, "Unable to delete goal")); } }
  return <div className="space-y-6"><header><h1 className="text-2xl font-semibold text-slate-800">Goals</h1><p className="mt-1 text-slate-500">Turn your study plans into consistent progress.</p></header>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-600">{error}</p>}<form onSubmit={add} className="flex flex-wrap gap-3 rounded-2xl border border-cream-200 bg-white p-4 shadow-sm"><input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Add a new goal" className="min-w-48 flex-1 rounded-xl border border-slate-200 px-3 py-2" /><input type="date" value={targetDate} onChange={(e) => setTargetDate(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2" /><button className="flex items-center gap-2 rounded-xl bg-lavender-600 px-4 py-2 font-semibold text-white"><Plus size={16} /> Add goal</button></form><div className="grid gap-4 md:grid-cols-2">{goals.map((goal) => <article key={goal.id} className="rounded-2xl border border-cream-200 bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><button onClick={() => void complete(goal)} disabled={goal.status === "COMPLETED"} className={`mt-0.5 rounded-lg p-1.5 ${goal.status === "COMPLETED" ? "bg-emerald-100 text-emerald-600" : "bg-lavender-100 text-lavender-600"}`}><Check size={16} /></button><div className="min-w-0 flex-1"><h2 className={`font-semibold ${goal.status === "COMPLETED" ? "text-slate-400 line-through" : "text-slate-800"}`}>{goal.title}</h2><p className="mt-1 text-sm text-slate-500">{goal.targetDate ? `Target: ${new Date(`${goal.targetDate}T12:00`).toLocaleDateString()}` : "No target date"}</p></div><button onClick={() => void remove(goal.id)} className="text-slate-400 hover:text-red-600"><Trash2 size={16} /></button></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-cream-100"><div className="h-full bg-lavender-500" style={{ width: `${goal.progressPercent}%` }} /></div><p className="mt-2 text-xs text-slate-400">{goal.status === "COMPLETED" ? "Completed" : `${goal.progressPercent}% complete`}</p></article>)}{goals.length === 0 && <p className="text-sm text-slate-400">No goals yet. Add your first one above.</p>}</div></div>;
}
