import { useEffect, useState, type FormEvent } from "react";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { notesApi } from "../api/productivityApi";
import { extractErrorMessage } from "../api/client";
import type { Note } from "../types/academic";

export default function NotesPage() {
  const [notes, setNotes] = useState<Note[]>([]); const [editing, setEditing] = useState<Note | null>(null); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [showEditor, setShowEditor] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { notesApi.list().then(setNotes).catch((e) => setError(extractErrorMessage(e, "Unable to load notes"))); }, []);
  function begin(note?: Note) { setEditing(note ?? null); setTitle(note?.title ?? ""); setBody(note?.body ?? ""); setShowEditor(true); }
  function close() { setShowEditor(false); setEditing(null); setTitle(""); setBody(""); }
  async function save(e: FormEvent) { e.preventDefault(); try { const note = editing ? await notesApi.update(editing.id, { title, body }) : await notesApi.create({ title, body }); setNotes((v) => editing ? v.map((x) => x.id === note.id ? note : x) : [note, ...v]); close(); } catch (err) { setError(extractErrorMessage(err, "Unable to save note")); } }
  async function remove(id: number) { try { await notesApi.delete(id); setNotes((v) => v.filter((x) => x.id !== id)); } catch (err) { setError(extractErrorMessage(err, "Unable to delete note")); } }
  return <div className="space-y-6"><header className="flex items-center justify-between"><div><h1 className="text-2xl font-semibold text-slate-800">Notes</h1><p className="mt-1 text-slate-500">Keep your study ideas organized.</p></div><button onClick={() => begin()} className="flex items-center gap-2 rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16} /> New note</button></header>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-600">{error}</p>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{notes.map((note) => <article key={note.id} className="rounded-2xl border border-cream-200 bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><h2 className="font-semibold text-slate-800">{note.title}</h2><div className="flex gap-2"><button onClick={() => begin(note)} className="text-slate-400 hover:text-brand-600"><Pencil size={16} /></button><button onClick={() => void remove(note.id)} className="text-slate-400 hover:text-red-600"><Trash2 size={16} /></button></div></div><p className="mt-3 line-clamp-5 whitespace-pre-wrap text-sm text-slate-500">{note.body}</p><p className="mt-4 text-xs text-slate-400">Updated {new Date(note.updatedAt).toLocaleDateString()}</p></article>)}</div>{showEditor && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/30 p-4"><form onSubmit={save} className="w-full max-w-xl space-y-4 rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-lg font-semibold">{editing ? "Edit note" : "New note"}</h2><input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Title" className="w-full rounded-xl border border-slate-200 px-3 py-2" /><textarea required value={body} onChange={(e) => setBody(e.target.value)} placeholder="Write your note…" rows={9} className="w-full rounded-xl border border-slate-200 px-3 py-2" /><div className="flex justify-end gap-2"><button type="button" onClick={close} className="rounded-xl px-4 py-2 text-slate-500">Cancel</button><button className="rounded-xl bg-brand-600 px-4 py-2 font-semibold text-white">Save note</button></div></form></div>}</div>;
}
