import { useEffect, useState } from "react";
import { Pause, Play, Timer } from "lucide-react";
import { sessionsApi } from "../api/productivityApi";
import { extractErrorMessage } from "../api/client";
import type { StudySession } from "../types/academic";

export default function StudyTimerPage() {
  const [sessions, setSessions] = useState<StudySession[]>([]); const [active, setActive] = useState<StudySession | null>(null); const [seconds, setSeconds] = useState(0); const [error, setError] = useState<string | null>(null);
  useEffect(() => { sessionsApi.list().then((items) => { setSessions(items); const current = items.find((item) => item.inProgress) ?? null; setActive(current); if (current) setSeconds(Math.floor((Date.now() - new Date(current.startTime).getTime()) / 1000)); }).catch((e) => setError(extractErrorMessage(e, "Unable to load study sessions"))); }, []);
  useEffect(() => { if (!active) return; const timer = window.setInterval(() => setSeconds((v) => v + 1), 1000); return () => window.clearInterval(timer); }, [active]);
  async function toggle() { try { if (active) { const saved = await sessionsApi.stop(active.id); setSessions((v) => [saved, ...v.filter((x) => x.id !== saved.id)]); setActive(null); } else { const saved = await sessionsApi.start(); setActive(saved); setSeconds(0); } } catch (err) { setError(extractErrorMessage(err, "Unable to update timer")); } }
  const display = `${String(Math.floor(seconds / 3600)).padStart(2, "0")}:${String(Math.floor((seconds % 3600) / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
  return <div className="mx-auto max-w-2xl space-y-6"><header className="text-center"><h1 className="text-2xl font-semibold text-slate-800">Study Timer</h1><p className="mt-1 text-slate-500">Focus now; your study session is saved when you stop.</p></header>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-600">{error}</p>}<section className="rounded-3xl border border-cream-200 bg-white p-10 text-center shadow-sm"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-brand-100 text-brand-600"><Timer size={30} /></div><p className="mt-6 font-mono text-5xl font-semibold tracking-tight text-slate-800">{display}</p><p className="mt-3 text-sm text-slate-400">{active ? "Study session in progress" : "Ready when you are"}</p><button onClick={() => void toggle()} className="mx-auto mt-8 flex items-center gap-2 rounded-xl bg-brand-600 px-5 py-3 font-semibold text-white">{active ? <Pause size={18} /> : <Play size={18} />} {active ? "Stop and save" : "Start studying"}</button></section><section className="rounded-2xl border border-cream-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-800">Recent sessions</h2><div className="mt-3 space-y-2">{sessions.filter((item) => !item.inProgress).slice(0, 5).map((item) => <div key={item.id} className="flex justify-between text-sm text-slate-500"><span>{new Date(item.startTime).toLocaleDateString()}</span><span>{item.durationMinutes ?? 0} minutes</span></div>)}{sessions.filter((item) => !item.inProgress).length === 0 && <p className="text-sm text-slate-400">Completed sessions will appear here.</p>}</div></section></div>;
}
